# Generated by Django 5.2.4 on 2025-10-28 00:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Results",
            fields=[
                ("ResultID", models.AutoField(primary_key=True, serialize=False)),
                ("ResultDateTime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ODM2_Results",
            },
        ),
        migrations.CreateModel(
            name="CV_ActionType",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_ActionType",
            },
        ),
        migrations.CreateModel(
            name="CV_AnnotationType",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_AnnotationType",
            },
        ),
        migrations.CreateModel(
            name="CV_CategoricalValue",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_CategoricalValue",
            },
        ),
        migrations.CreateModel(
            name="CV_RelationshipType",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_RelationshipType",
            },
        ),
        migrations.CreateModel(
            name="CV_ResultsType",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_ResultsType",
            },
        ),
        migrations.CreateModel(
            name="CV_SamplingFeatureType",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_SamplingFeatureType",
            },
        ),
        migrations.CreateModel(
            name="CV_SiteType",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_SiteType",
            },
        ),
        migrations.CreateModel(
            name="CV_Units",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_Units",
            },
        ),
        migrations.CreateModel(
            name="CV_VariableName",
            fields=[
                ("Term", models.CharField(max_length=255, unique=True)),
                (
                    "Name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Definition", models.TextField(blank=True, null=True)),
                ("Category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SourceVocabularyURI",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "CV_VariableName",
            },
        ),
        migrations.CreateModel(
            name="Equipments",
            fields=[
                ("EquipmentID", models.AutoField(primary_key=True, serialize=False)),
                ("EquipmentName", models.CharField(max_length=255)),
                ("Description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ODM2_Equipments",
            },
        ),
        migrations.CreateModel(
            name="FeatureActions",
            fields=[
                (
                    "FeatureActionID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "ODM2_FeatureActions",
            },
        ),
        migrations.CreateModel(
            name="SamplingFeatures",
            fields=[
                (
                    "SamplingFeatureID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "SamplingFeatureUUID",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("SamplingFeatureCode", models.CharField(max_length=255)),
                (
                    "SamplingFeatureName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("SamplingFeatureDescription", models.TextField(blank=True, null=True)),
                ("FeatureGeometry", models.TextField(blank=True, null=True)),
                ("Elevation_m", models.FloatField(blank=True, null=True)),
                (
                    "SamplingFeatureTypeCV",
                    models.ForeignKey(
                        db_column="SamplingFeatureTypeCV",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.cv_samplingfeaturetype",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_SamplingFeatures",
            },
        ),
        migrations.CreateModel(
            name="CategoricalResults",
            fields=[
                (
                    "ResultID",
                    models.OneToOneField(
                        db_column="ResultID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="odm2_data.results",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_CategoricalResults",
            },
        ),
        migrations.CreateModel(
            name="MeasurementResults",
            fields=[
                (
                    "ResultID",
                    models.OneToOneField(
                        db_column="ResultID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="odm2_data.results",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_MeasurementResults",
            },
        ),
        migrations.CreateModel(
            name="TimeSeriesResults",
            fields=[
                (
                    "ResultID",
                    models.OneToOneField(
                        db_column="ResultID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="odm2_data.results",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_TimeSeriesResults",
            },
        ),
        migrations.CreateModel(
            name="Actions",
            fields=[
                ("ActionID", models.AutoField(primary_key=True, serialize=False)),
                ("BeginDateTime", models.DateTimeField(blank=True, null=True)),
                ("EndDateTime", models.DateTimeField(blank=True, null=True)),
                ("ActionDescription", models.TextField(blank=True, null=True)),
                (
                    "ActionTypeCV",
                    models.ForeignKey(
                        db_column="ActionTypeCV",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.cv_actiontype",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_Actions",
            },
        ),
        migrations.AddField(
            model_name="results",
            name="ResultTypeCV",
            field=models.ForeignKey(
                db_column="ResultTypeCV",
                on_delete=django.db.models.deletion.CASCADE,
                to="odm2_data.cv_resultstype",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentUsed",
            fields=[
                ("BridgeID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ActionID",
                    models.ForeignKey(
                        db_column="ActionID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.actions",
                    ),
                ),
                (
                    "EquipmentID",
                    models.ForeignKey(
                        db_column="EquipmentID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.equipments",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_EquipmentUsed",
            },
        ),
        migrations.AddField(
            model_name="results",
            name="FeatureActionID",
            field=models.ForeignKey(
                db_column="FeatureActionID",
                on_delete=django.db.models.deletion.CASCADE,
                to="odm2_data.featureactions",
            ),
        ),
        migrations.AddField(
            model_name="featureactions",
            name="ActionID",
            field=models.ForeignKey(
                db_column="ActionID",
                on_delete=django.db.models.deletion.CASCADE,
                to="odm2_data.actions",
            ),
        ),
        migrations.CreateModel(
            name="RelatedResults",
            fields=[
                ("RelationID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "VersionCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "RelatedResultSequenceNumber",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "RelatedResultID",
                    models.ForeignKey(
                        db_column="RelatedResultID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_related",
                        to="odm2_data.results",
                    ),
                ),
                (
                    "RelationshipTypeCV",
                    models.ForeignKey(
                        db_column="RelationshipTypeCV",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.cv_relationshiptype",
                    ),
                ),
                (
                    "ResultID",
                    models.ForeignKey(
                        db_column="ResultID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_result",
                        to="odm2_data.results",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_RelatedResults",
            },
        ),
        migrations.CreateModel(
            name="Sites",
            fields=[
                (
                    "SamplingFeatureID",
                    models.OneToOneField(
                        db_column="SamplingFeatureID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="odm2_data.samplingfeatures",
                    ),
                ),
                ("Latitude", models.FloatField(blank=True, null=True)),
                ("Longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "ODM2_Sites",
            },
        ),
        migrations.CreateModel(
            name="SamplingFeatureAnnotations",
            fields=[
                ("BridgeID", models.AutoField(primary_key=True, serialize=False)),
                ("AnnotationDateTime", models.DateTimeField(blank=True, null=True)),
                (
                    "AnnotationTypeCV",
                    models.ForeignKey(
                        db_column="AnnotationTypeCV",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.cv_annotationtype",
                    ),
                ),
                (
                    "SamplingFeatureID",
                    models.ForeignKey(
                        db_column="SamplingFeatureID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.samplingfeatures",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_SamplingFeatureAnnotations",
            },
        ),
        migrations.CreateModel(
            name="RelatedFeatures",
            fields=[
                ("RelationID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "RelationshipTypeCV",
                    models.ForeignKey(
                        db_column="RelationshipTypeCV",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.cv_relationshiptype",
                    ),
                ),
                (
                    "RelatedFeatureID",
                    models.ForeignKey(
                        db_column="RelatedFeatureID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatedfeatures_as_object",
                        to="odm2_data.samplingfeatures",
                    ),
                ),
                (
                    "SamplingFeatureID",
                    models.ForeignKey(
                        db_column="SamplingFeatureID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatedfeatures_as_subject",
                        to="odm2_data.samplingfeatures",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_RelatedFeatures",
            },
        ),
        migrations.AddField(
            model_name="featureactions",
            name="SamplingFeatureID",
            field=models.ForeignKey(
                db_column="SamplingFeatureID",
                on_delete=django.db.models.deletion.CASCADE,
                to="odm2_data.samplingfeatures",
            ),
        ),
        migrations.CreateModel(
            name="Units",
            fields=[
                ("UnitsID", models.AutoField(primary_key=True, serialize=False)),
                ("UnitsName", models.CharField(max_length=255)),
                (
                    "UnitsTypeCV",
                    models.ForeignKey(
                        db_column="UnitsTypeCV",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.cv_units",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_Units",
            },
        ),
        migrations.AddField(
            model_name="results",
            name="UnitsID",
            field=models.ForeignKey(
                blank=True,
                db_column="UnitsID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="odm2_data.units",
            ),
        ),
        migrations.CreateModel(
            name="Variables",
            fields=[
                ("VariableID", models.AutoField(primary_key=True, serialize=False)),
                ("VariableCode", models.CharField(max_length=100, unique=True)),
                (
                    "VariableNameCV",
                    models.ForeignKey(
                        db_column="VariableNameCV",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odm2_data.cv_variablename",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_Variables",
            },
        ),
        migrations.AddField(
            model_name="results",
            name="VariableID",
            field=models.ForeignKey(
                db_column="VariableID",
                on_delete=django.db.models.deletion.CASCADE,
                to="odm2_data.variables",
            ),
        ),
        migrations.CreateModel(
            name="CategoricalResultValues",
            fields=[
                ("ValueID", models.AutoField(primary_key=True, serialize=False)),
                ("DataValue", models.CharField(blank=True, max_length=255, null=True)),
                ("ValueDateTime", models.DateTimeField()),
                ("hasMeasurement", models.BooleanField(default=False)),
                (
                    "DataValueCV",
                    models.ForeignKey(
                        blank=True,
                        db_column="DataValueCV",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="odm2_data.cv_categoricalvalue",
                    ),
                ),
                (
                    "ResultID",
                    models.ForeignKey(
                        db_column="ResultID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Values",
                        to="odm2_data.categoricalresults",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_CategoricalResultValues",
            },
        ),
        migrations.CreateModel(
            name="MeasurementResultValues",
            fields=[
                ("ValueID", models.AutoField(primary_key=True, serialize=False)),
                ("DataValue", models.FloatField()),
                ("ValueDateTime", models.DateTimeField()),
                ("hasCategorical", models.BooleanField(default=False)),
                (
                    "ResultID",
                    models.ForeignKey(
                        db_column="ResultID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Values",
                        to="odm2_data.measurementresults",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_MeasurementResultValues",
            },
        ),
        migrations.CreateModel(
            name="TimeSeriesResultValues",
            fields=[
                ("ValueID", models.AutoField(primary_key=True, serialize=False)),
                ("DataValue", models.FloatField()),
                ("ValueDateTime", models.DateTimeField()),
                (
                    "ResultID",
                    models.ForeignKey(
                        db_column="ResultID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Values",
                        to="odm2_data.timeseriesresults",
                    ),
                ),
            ],
            options={
                "db_table": "ODM2_TimeSeriesResultValues",
            },
        ),
        migrations.AddIndex(
            model_name="actions",
            index=models.Index(
                fields=["ActionTypeCV", "BeginDateTime"],
                name="ODM2_Action_ActionT_98f2a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipmentused",
            index=models.Index(
                fields=["ActionID", "EquipmentID"],
                name="ODM2_Equipm_ActionI_7b9ac6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="equipmentused",
            unique_together={("ActionID", "EquipmentID")},
        ),
        migrations.AddIndex(
            model_name="relatedresults",
            index=models.Index(
                fields=["ResultID", "RelationshipTypeCV"],
                name="ODM2_Relate_ResultI_b507c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relatedresults",
            index=models.Index(
                fields=["RelatedResultID"], name="ODM2_Relate_Related_aa9f61_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relatedresults",
            unique_together={("ResultID", "RelationshipTypeCV", "RelatedResultID")},
        ),
        migrations.AddField(
            model_name="sites",
            name="SiteTypeCV",
            field=models.ForeignKey(
                db_column="SiteTypeCV",
                on_delete=django.db.models.deletion.CASCADE,
                to="odm2_data.cv_sitetype",
            ),
        ),
        migrations.AddIndex(
            model_name="samplingfeatures",
            index=models.Index(
                fields=["SamplingFeatureCode"], name="ODM2_Sampli_Samplin_9642d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="samplingfeatures",
            index=models.Index(
                fields=["SamplingFeatureTypeCV"], name="ODM2_Sampli_Samplin_b9cfed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="samplingfeatureannotations",
            index=models.Index(
                fields=["SamplingFeatureID", "AnnotationTypeCV"],
                name="ODM2_Sampli_Samplin_255d7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relatedfeatures",
            index=models.Index(
                fields=["SamplingFeatureID", "RelationshipTypeCV"],
                name="ODM2_Relate_Samplin_c88c12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relatedfeatures",
            index=models.Index(
                fields=["RelatedFeatureID"], name="ODM2_Relate_Related_f0db33_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="relatedfeatures",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("SamplingFeatureID", models.F("RelatedFeatureID")), _negated=True
                ),
                name="ck_relatedfeatures_no_self_loop",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relatedfeatures",
            unique_together={
                ("SamplingFeatureID", "RelationshipTypeCV", "RelatedFeatureID")
            },
        ),
        migrations.AddIndex(
            model_name="featureactions",
            index=models.Index(
                fields=["SamplingFeatureID", "ActionID"],
                name="ODM2_Featur_Samplin_af4016_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featureactions",
            unique_together={("SamplingFeatureID", "ActionID")},
        ),
        migrations.AddIndex(
            model_name="results",
            index=models.Index(
                fields=["FeatureActionID", "VariableID"],
                name="ODM2_Result_Feature_c945ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="results",
            index=models.Index(
                fields=["ResultTypeCV"], name="ODM2_Result_ResultT_65a2d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoricalresultvalues",
            index=models.Index(
                fields=["ValueDateTime"], name="ODM2_Catego_ValueDa_04a035_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="categoricalresultvalues",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("DataValue__isnull", False),
                    ("DataValueCV__isnull", False),
                    _connector="OR",
                ),
                name="ck_catval_value_or_cv_not_null",
            ),
        ),
        migrations.AddIndex(
            model_name="measurementresultvalues",
            index=models.Index(
                fields=["ValueDateTime"], name="ODM2_Measur_ValueDa_315298_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeseriesresultvalues",
            index=models.Index(
                fields=["ValueDateTime"], name="ODM2_TimeSe_ValueDa_5ff7f7_idx"
            ),
        ),
    ]
